var patientKeys = {
    'first_name': { 'display' : 'First name',
                    'type': 'short_text',
                    'size': 20 },
    'last_name': { 'display' : 'Last name',
                   'type': 'short_text',
                   'size': 20 },
    'phone' : { 'display' : 'Phone number',
                'type': 'phone',
                'size': 15 },
    'dob' : { 'display' : 'Date of birth',
              'type': 'date' },
    'address' : { 'display' : 'Address',
                  'type': 'text' },
    'email' : { 'display' : 'Email',
                'type': 'email',
                'size': 20 },
    'gender' : { 'display' : 'Gender',
                 'type': 'options',
                 'options': {
                     'male': { 'display': 'Male' },
                     'female': { 'display': 'Female' },
                 } },
};

var visitKeys = {
    'date': { 'display': 'Date',
              'type': 'text',
              'editable': false},
    'bp_low': { 'display': 'Blood Pressure (low)',
                'type': 'number' },
    'bp_high': { 'display': 'Blood Pressure (high)',
                 'type': 'number' },
    'hr': { 'display': 'Heart Rate',
            'type': 'number' },
    'weight': { 'display': 'Weight',
                'type': 'number' },
    'height': { 'display': 'Height',
                'type': 'number' },
    'symptoms': { 'display': 'Symptoms',
                  'type': 'text' },
    'diagnosis': { 'display': 'Diagnosis',
                   'type': 'text' },
    'prescriptions': { 'display': 'Prescriptions',
                       'type': 'prescriptions' },
    'therapy': { 'display': 'Therapy',
                 'type': 'therapy' },
    'cost': { 'display': 'Cost',
              'type': 'cost' },
    'next_visit': { 'display': 'Next Visit',
                    'type': 'date' },
    'remarks' : { 'display': 'Remarks',
                  'type': 'text' },
};

var prescriptionKeys = {
    'name' : { 'display' : 'Name',
               'type': 'short_text',
               'size': 30 },
    'unit_price' : { 'display' : 'Unit price',
                     'type': 'number' },
};
