var STRINGS = {
    order: 'ลำดับ',
    view: 'ดูประวัติ',
    first_name: 'ชื่อ',
    last_name: 'นามสกุล',
    phone_number: 'เบอร์โทรศัพท์',
    visit_info: 'ข้อมูลการรักษา',
    save: 'บันทึก',
    new_visit: 'หาหมอวันนี้',
    doctor_queue: 'เข้าคิวพบแพทย์',
    delete: 'ลบ',
    finish: 'เสร็จสิ้นการตรวจ',
    add_prescription: 'เพิ่มยา',
    add_treatment: 'เพิ่มกายภาพบำบัด',
    auto_cost: 'คำนวนค่ารักษา',
    pick_report_date: 'เลือกวันที่จะดูรายงาน',
    enter_first_and_last_names: 'โปรดกรอกชื่อและนามสกุลให้ครบ',
    enter_valid_date: 'โปรดใส่วันที่ให้ถูกต้อง (วว/ดด/ปปปป)',
    cannot_queue_patient: 'ข้อมูลคนใข้ไม่ถูกต้อง ไม่สามารถเข้าคิวได้',
    patient_not_found: 'ไม่พบคนไข้',
    cost_is_zero: 'ค่ารักษาพยาบาล 0 บาท ดำเนินการต่อไหม?',
    patient: 'คนใข้',
    patient_unit: 'คน',
    total_revenue: 'รายได้รวม',
    currency: 'บาท',
    select: 'เลือก...',
    new_prescription: 'เพิ่มชนิดยา',
    new_treatment: 'เพิ่มชนิดกายภาพบำบัด',
    have_you_received_payment1: 'ได้รับเงิน',
    have_you_received_payment2: 'จากคนใข้แล้วใช่ไหม?',
    no_results: 'ไม่พบคนไข้',
    update_failed: 'บันทึกข้อมูลไม่สำเร็จ',
    update_succeeded: 'บันทึกข้อมูลเรียบร้อย',
    queuing_failed: 'เข้าคิวไม่สำเร็จ',
    queuing_succeeded: 'เข้าคิวเรียบร้อย',
};
