var STRINGS = {
    order: 'ลำดับ',
    view: 'ดูประวัติ',
    first_name: 'ชื่อ',
    last_name: 'นามสกุล',
    phone_number: 'เบอร์โทรศัพท์',
    visit_info: 'ข้อมูลการรักษา',
    save: 'บันทึก',
    new_visit: 'หาหมอวันนี้',
    doctor_queue: 'เข้าคิวพบแพทย์',
    delete: 'ลบ',
    clear: 'ลบทั้งหมด',
    new_image: 'เพิ่มภาพใหม่',
    finish: 'เสร็จสิ้นการตรวจ',
    add_prescription: 'เพิ่มยา',
    add_equipment: 'เพิ่มอุปกรณ์',
    add_treatment: 'เพิ่มกายภาพบำบัด/ฝังเข็ม',
    add_image: 'เพิ่มรูปภาพ',
    auto_cost: 'คำนวนค่ารักษา',
    pick_report_date: 'เลือกวันที่จะดูรายงาน',
    enter_first_and_last_names: 'โปรดกรอกชื่อและนามสกุลให้ครบ',
    enter_valid_date: 'โปรดใส่วันที่ให้ถูกต้อง (วว/ดด/ปปปป)',
    cannot_queue_patient: 'ข้อมูลคนใข้ไม่ถูกต้อง ไม่สามารถเข้าคิวได้',
    patient_not_found: 'ไม่พบคนไข้',
    cost_is_zero: 'ค่ารักษาพยาบาล 0 บาท ดำเนินการต่อไหม?',
    remove_image: 'ลบรูปนี้ออกจากระบบ?',
    please_select_image_file: 'โปรดเลือกไฟล์รูปภาพจากเครื่อง',
    please_enter_image_name: 'โปรดกำหนดชื่อภาพนี้',
    patient: 'คนใข้',
    patient_unit: 'คน',
    total_revenue: 'รายได้รวม',
    currency: 'บาท',
    select: 'เลือก...',
    select_to_add: 'เลือกเพื่อเพิ่ม...',
    new_prescription: 'เพิ่มชนิดยา',
    new_treatment: 'เพิ่มชนิดกายภาพบำบัด/ฝังเข็ม',
    new_procedure: 'เพิ่มต้นฉบับ',
    new_equipment: 'เพิ่มอุปกรณ์',
    have_you_received_payment1: 'ได้รับเงิน',
    have_you_received_payment2: 'จากคนใข้แล้วใช่ไหม?',
    no_results: 'ไม่พบคนไข้',
    update_failed: 'บันทึกข้อมูลไม่สำเร็จ',
    update_succeeded: 'บันทึกข้อมูลเรียบร้อย',
    queuing_failed: 'เข้าคิวไม่สำเร็จ',
    queuing_succeeded: 'เข้าคิวเรียบร้อย',
    deletion_failed: 'ลบข้อมูลไม่สำเร็จ',
    deletion_succeeded: 'ลบข้อมูลเรียบร้อย',
    new_image_title: 'ภาพใหม่',
    image_title: 'ภาพร่างกาย',
    browse_file: 'เลือกไฟล์',
    horizontal_divider: '\n==========================\n\n',
    unit_price: 'ราคาต่อหน่วย',

    invalid_bp: 'ค่าความดันโลหิตไม่ถูกต้อง',
    invalid_hr: 'ค่าชีพจรไม่ถูกต้อง',
    invalid_weight: 'น้ำหนักไม่ถูกต้อง',
    invalid_height: 'ส่วนสูงไม่ถูกต้อง',
    invalid_cost: 'ค่ารักษาไม่ถูกต้อง',
    invalid_next_visit: 'วันที่นัดครั้งหน้าไม่ถูกต้อง',
    invalid_phone: 'เบอร์โทรศัพท์ไม่ถูกต้อง',
    invalid_dob: 'วันเดือนปีเกิดไม่ถูกต้อง',
    invalid_email: 'อีเมล์ไม่ถูกต้อง',
};
