var STRINGS = {
    order: 'ลำดับ',
    view: 'ดูประวัติ',
    first_name: 'ชื่อ',
    last_name: 'นามสกุล',
    phone_number: 'เบอร์โทรศัพท์',
    save: 'บันทึก',
    new_visit: 'หาหมอวันนี้',
    doctor_queue: 'เข้าคิวพบแพทย์',
    delete: 'ลบ',
    finish: 'เสร็จสิ้นการตรวจ',
    add_prescription: 'เพิ่มยา',
    add_treatment: 'เพิ่มกายภาพบำบัด',
    auto_cost: 'คำนวนค่ารักษา',
    pick_report_date: 'เลือกวันที่จะดูรายงาน',
    enter_valid_date: 'โปรดใส่วันที่ให้ถูกต้อง (วว/ดด/ปปปป)',
    patient: 'คนใข้',
    patient_unit: 'คน',
    total_revenue: 'รายได้รวม',
    currency: 'บาท',
    select: 'เลือก...',
    new_prescription: 'เพิ่มชนิดยา',
    new_treatment: 'เพิ่มชนิดกายภาพบำบัด',
    have_you_recieved_payment1: 'ได้รับเงิน',
    have_you_recieved_payment2: 'จากคนใข้แล้วใช่ไหม?',
};
